from data_source.core.scraper import BaseScraper
from data_source.scrapers.nfe import (
    NFeDiversosScraper,
    NFeEsquemasXMLScraper,
    NFeInformesTecnicosScraper,
    NFeManuaisScraper,
    NFeNotasTecnicasScraper,
    NFeScraper,
)
from data_source.scrapers.nfse import NFSeScraper
from data_source.scrapers.svrs import (
    SVRSBPeDocumentosScraper,
    SVRSCTeDocumentosScraper,
    SVRSDCeDocumentosScraper,
    SVRSDIFALDocumentosScraper,
    SVRSMDFeDocumentosScraper,
    SVRSNF3eDocumentosScraper,
    SVRSNFABIDocumentosScraper,
    SVRSNFAgDocumentosScraper,
    SVRSNFCeDocumentosScraper,
    SVRSNFComDocumentosScraper,
    SVRSNFeDocumentosScraper,
    SVRSNFFDocumentosScraper,
    SVRSNFGasDocumentosScraper,
    SVRSONEDocumentosScraper,
    SVRSPESDocumentosScraper,
)

REGISTRY: dict[str, type[BaseScraper]] = {
    NFeEsquemasXMLScraper.context: NFeEsquemasXMLScraper,
    NFeNotasTecnicasScraper.context: NFeNotasTecnicasScraper,
    NFeInformesTecnicosScraper.context: NFeInformesTecnicosScraper,
    NFeDiversosScraper.context: NFeDiversosScraper,
    NFeManuaisScraper.context: NFeManuaisScraper,
    NFSeScraper.context: NFSeScraper,
    SVRSBPeDocumentosScraper.context: SVRSBPeDocumentosScraper,
    SVRSCTeDocumentosScraper.context: SVRSCTeDocumentosScraper,
    SVRSDCeDocumentosScraper.context: SVRSDCeDocumentosScraper,
    SVRSDIFALDocumentosScraper.context: SVRSDIFALDocumentosScraper,
    SVRSMDFeDocumentosScraper.context: SVRSMDFeDocumentosScraper,
    SVRSNF3eDocumentosScraper.context: SVRSNF3eDocumentosScraper,
    SVRSNFABIDocumentosScraper.context: SVRSNFABIDocumentosScraper,
    SVRSNFAgDocumentosScraper.context: SVRSNFAgDocumentosScraper,
    SVRSNFCeDocumentosScraper.context: SVRSNFCeDocumentosScraper,
    SVRSNFComDocumentosScraper.context: SVRSNFComDocumentosScraper,
    SVRSNFFDocumentosScraper.context: SVRSNFFDocumentosScraper,
    SVRSNFGasDocumentosScraper.context: SVRSNFGasDocumentosScraper,
    SVRSNFeDocumentosScraper.context: SVRSNFeDocumentosScraper,
    SVRSONEDocumentosScraper.context: SVRSONEDocumentosScraper,
    SVRSPESDocumentosScraper.context: SVRSPESDocumentosScraper,
}

__all__ = [
    "REGISTRY",
    "NFeDiversosScraper",
    "NFeEsquemasXMLScraper",
    "NFeInformesTecnicosScraper",
    "NFeManuaisScraper",
    "NFeNotasTecnicasScraper",
    "NFeScraper",
    "NFSeScraper",
    "SVRSBPeDocumentosScraper",
    "SVRSCTeDocumentosScraper",
    "SVRSDCeDocumentosScraper",
    "SVRSDIFALDocumentosScraper",
    "SVRSMDFeDocumentosScraper",
    "SVRSNF3eDocumentosScraper",
    "SVRSNFABIDocumentosScraper",
    "SVRSNFAgDocumentosScraper",
    "SVRSNFCeDocumentosScraper",
    "SVRSNFComDocumentosScraper",
    "SVRSNFFDocumentosScraper",
    "SVRSNFGasDocumentosScraper",
    "SVRSNFeDocumentosScraper",
    "SVRSONEDocumentosScraper",
    "SVRSPESDocumentosScraper",
]
